export default {
  extranetHost: "test-cloud.jdl.com",
  intranetHost: "test-lcp.jdl.com",
  buildEnv: "publictest",
  baseEnv: "test",
  baseStreamAccount: "",
  baseStreamCloudAccount: "",
  idaasLogoutDomain: "http://test-soms.jdl.com",
  gatewayOuterBaseApi: "http://lop-test.jdl.com",
  gatewayBaseApi: "http://test-api.jdl.com/",
  gatewayFileBaseApi: "http://lop-test.jdl.com/",
  gatewayUploadLopDn: "test.sdkfile.com",
  gatewayUploadLopDnXml: "test.sdkfile.com",
  gatewayPtnr: '{"appid":"test"}',
  gatewayPassportPtnr: '{"appid":"test_passport"}',
  gatewayPartnerMessageXmlBucket: "lcp.message.push.xml.test",
  gatewayPartnerMessageLopDn: "lop.data.processor.jd.com",
  docDescription: "/apiNewHand/7",
  docApiPublish: "/apiNewHand/9",
  docApiTest: "devSupport/115",
  docSdkCreate: "devSupport/34",
  domainErp: "//test.ssa.jd.com",
  docMessageListTag: "apiNewHand/103",
  idaasModifyPhone:
    "http://test-soms.jdl.com/static/modifyPhone.html?source=&tc=&returnUrl=",
  gatewayApiDecoupling: "http://lop-test.jdl.com",
  gatewayApiDecouplingOuter: "http://lop-test.jdl.com",
  gatewayApiDecouplingLop: "TEST_LOP_OPEN_APIDEPOT",
  gatewayLogDecouplingLop: "log.smartlog.jdl.com",
  gatewaySandboxApi: "http://lop-test.jd.com",
  jingMeAuthAlias: "lop-jdos-test",
  erpAuthReturn: "//test.ssa.jd.com/sso/login?ReturnUrl=",
  pkid: 1262,
  publicKey:
    "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSU136QnY23+oVLXPBjiQ+jHvAYqrmEQd9tx7NYcbH+EwIr6BLYFTdSXNckP7pE3r/WfB5g5fVZefLdCPB+VCnwv7mxWt9yuPzqp30dfV9JZ8UzaG/J161oFjYqWmfU3sU0MNE00S5XKbhQUyLew+CDshPCb/9unLuiqONkBKqeQIDAQAB\n-----END PUBLIC KEY-----",
};
