export default {
  extranetHost: "uat-cloud.jdl.com",
  intranetHost: "uat-lcp.jdl.com",
  buildEnv: "uat",
  baseEnv: "uat",
  baseStreamAccount: "JA2020_1222753",
  baseStreamCloudAccount: "JA2020_1222753",
  idaasLogoutDomain: "https://pre-account.jdl.com",
  gatewayOuterBaseApi: "http://uat-lop.jdl.com/",
  gatewayBaseApi: "http://uat-lop.jdl.com/",
  gatewayFileBaseApi: "http://uat-lop.jdl.com/",
  gatewayUploadLopDn: "lop.cloud.sdkfile.com",
  gatewayUploadLopDnXml: "lop.cloud.sdkfile.com",
  gatewayPtnr: '{"appid":"lop_erp"}',
  gatewayPassportPtnr: '{"appid":"lop_passport"}',
  gatewayPartnerMessageXmlBucket: "lcp.message.push.xml.uat",
  gatewayPartnerMessageLopDn: "lop.cloud.sdkfile.com",
  docDescription: "/apiNewHand/7",
  docApiPublish: "/apiNewHand/9",
  docApiTest: "devSupport/32",
  docSdkCreate: "devSupport/34",
  domainErp: "//ssa.jd.com",
  docMessageListTag: "devSupport/52791",
  idaasModifyPhone:
    "https://pre-account.jdl.com/static/modifyPhone.html?source=&tc=&returnUrl=",
  gatewayApiDecoupling: "http://uat-lop.jdl.com",
  gatewayApiDecouplingOuter: "https://uat-api.jdl.com",
  gatewayApiDecouplingLop: "UAT_LOP_OPEN_APIDEPOT",
  gatewayLogDecouplingLop: "log.smartlog.jdl.com",
  gatewaySandboxApi: "http://test-api.jdl.com",
  jingMeAuthAlias: "lop-uat",
  erpAuthReturn: "//ssa.jd.com/sso/login?ReturnUrl=",
  pkid: 3859,
  publicKey:
    "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC1STFb2ykBv18YGpt5QlcftFTt2aUGFTjBs86uliWK1c6dm7aWHEDnI3eqFonXl+XFgjl3r0SD84bd73VPYetkUiYUa8PQpqIt85jWrFUuYtOvrS1ispGnE4tEEsDnAFiIiLeA5mitqJo2Ing5lQ24GUKYVagA9t1YT10DA6uSiwIDAQAB\n-----END PUBLIC KEY-----",
};
